### ISSUE TITLE
Request: Launch params 

### ISSUE THREAD

**Issue by paperrain** [Limitspassed/ASAManager#1]
Hi, maybe I'm not seeing it, but an option to set custom launch parameters?

And as an addition maybe that if there is a repeated parameter, don't set it again.

Thanks

**Comment by Limitspassed** [comment]
Are you referring to the start.bat? The functionality is there to update start bat. If you're wanting a text box that reads the start.bat and allows you to make changes through the gui I can make that an option.

**Comment by paperrain** [comment]
> Are you referring to the start.bat? The functionality is there to update start bat. If you're wanting a text box that reads the start.bat and allows you to make changes through the gui I can make that an option.

Yes, that's exactly what I mean, to have a text box to edit that content. Also, do you update the start.bat if you change something, right?

Also, I want to report this: if you include spaces in the 'Server Name' when starting the server, it doesn't recognize the complete name

**Comment by Limitspassed** [comment]
I can add the ability to directly edit the bat. The name issue is because it's not put in quotes so it sees spaces as a second command on the start.bat. I can adjust to make the name in a string like "server name with spaces". Some of the fields yes. Some of the fields don't work in the start.bat so I omitted them. You can change the gameusersettings.ini to change most things. That's where the parameters get passed to and stored.

**Comment by paperrain** [comment]
> I can add the ability to directly edit the bat. The name issue is because it's not put in quotes so it sees spaces as a second command on the start.bat. I can adjust to make the name in a string like "server name with spaces". Some of the fields yes. Some of the fields don't work in the start.bat so I omitted them. You can change the gameusersettings.ini to change most things. That's where the parameters get passed to and stored.

I don't mind editing the bat file manually, as the parameters I have don't usually change frequently. The only thing I wouldn't like is if everything gets erased if it's updated, that's what I meant

**Comment by Limitspassed** [comment]
> > I can add the ability to directly edit the bat. The name issue is because it's not put in quotes so it sees spaces as a second command on the start.bat. I can adjust to make the name in a string like "server name with spaces". Some of the fields yes. Some of the fields don't work in the start.bat so I omitted them. You can change the gameusersettings.ini to change most things. That's where the parameters get passed to and stored.
> 
> I don't mind editing the bat file manually, as the parameters I have don't usually change frequently. The only thing I wouldn't like is if everything gets erased if it's updated, that's what I meant

I gotcha. No that will not be updated. It's only updated if you press the button update start.bat.

**Comment by paperrain** [comment]
Thanks
